/* ============================================================
   HTML & DOM — lesson manifest
   ------------------------------------------------------------
   The single source of truth for this course's order. Every
   lesson page, the course map, the gating logic and the lesson
   hub all read from this list.
   ============================================================ */
window.TeachLessons = [
  { n: 1, id: "elements-attributes-and-syntax", file: "lessons/0001-elements-attributes-and-syntax.html", title: "Elements, attributes, and syntax", topic: "Markup & Semantic Structure", anim: "Layers" },
  { n: 2, id: "semantic-structure-and-landmarks", file: "lessons/0002-semantic-structure-and-landmarks.html", title: "Semantic structure and landmarks", topic: "Markup & Semantic Structure", anim: "Layers" },
  { n: 3, id: "the-dom-tree-representation", file: "lessons/0003-the-dom-tree-representation.html", title: "The DOM tree representation", topic: "The Document Object Model", anim: "Layers" },
  { n: 4, id: "nodes-elements-and-relationships", file: "lessons/0004-nodes-elements-and-relationships.html", title: "Nodes, elements, and relationships", topic: "The Document Object Model", anim: "Layers" },
  { n: 5, id: "forms-inputs-and-submission", file: "lessons/0005-forms-inputs-and-submission.html", title: "Forms, inputs, and submission", topic: "Forms & User Input", anim: "Layers" },
  { n: 6, id: "tables-media-and-embedded-content", file: "lessons/0006-tables-media-and-embedded-content.html", title: "Tables, media, and embedded content", topic: "Forms & Media", anim: "Layers" },
  { n: 7, id: "accessibility-roles-and-aria-basics", file: "lessons/0007-accessibility-roles-and-aria-basics.html", title: "Accessibility roles and ARIA basics", topic: "Accessibility & Inspection", anim: "Layers" },
  { n: 8, id: "inspecting-and-modifying-the-dom", file: "lessons/0008-inspecting-and-modifying-the-dom.html", title: "Inspecting and modifying the DOM", topic: "Accessibility & Inspection", anim: "Layers" }
];

/* ============================================================
   HTML & DOM — glossary
   ------------------------------------------------------------
   The vocabulary of this course, grouped into sections.
   ============================================================ */
window.TeachGlossary = [
  {
    id: "markup", title: "Markup & Semantic Structure",
    terms: [
      { term: "Semantic HTML", def: "The practice of using HTML tags that reinforce the structural meaning of content rather than merely its presentation.", lesson: 2, tags: ["semantics"] },
      { term: "Landmark element", def: "Major structural HTML5 tags (main, nav, header, footer, aside) recognized by screen readers for navigation.", lesson: 2, tags: ["a11y"] },
      { term: "Void element", def: "An element (like img, input, br, hr) that cannot have children and never uses a closing tag.", lesson: 1, tags: ["syntax"] },
      { term: "Attribute", def: "A key-value pair placed inside an opening tag providing metadata or configuration to the element.", lesson: 1, tags: ["syntax"] }
    ]
  },
  {
    id: "dom-tree", title: "The Document Object Model",
    terms: [
      { term: "DOM", def: "Document Object Model: a live in-memory tree representation of an HTML document created by the browser.", lesson: 3, tags: ["dom"] },
      { term: "Node", def: "The generic base interface for all objects in the DOM tree, including elements, text chunks, and comments.", lesson: 4, tags: ["dom"] },
      { term: "Element", def: "A specific node type corresponding to an HTML tag, possessing attributes, tag names, and child elements.", lesson: 4, tags: ["dom"] },
      { term: "DOM parsing", def: "The process where a browser tokenizes raw HTML markup bytes into tokens and constructs tree nodes.", lesson: 3, tags: ["browser"] }
    ]
  },
  {
    id: "forms-inputs", title: "Forms & User Input",
    terms: [
      { term: "Form element", def: "An interactive document section (<form>) collecting user inputs and submitting them to a server.", lesson: 5, tags: ["forms"] },
      { term: "Label association", def: "Linking an input to a <label> using matching for and id attributes for accessibility and touch targets.", lesson: 5, tags: ["a11y","forms"] },
      { term: "Client validation", def: "Browser-enforced constraints (required, type=email, pattern) checked before form submission.", lesson: 5, tags: ["forms"] },
      { term: "Responsive image", def: "An image implementation (<picture> or srcset) serving optimized file sizes tailored to display density.", lesson: 6, tags: ["media"] }
    ]
  },
  {
    id: "accessibility", title: "Accessibility & Inspection",
    terms: [
      { term: "Accessibility tree", def: "A specialized tree generated by browsers from the DOM exposing names, roles, and states to screen readers.", lesson: 7, tags: ["a11y"] },
      { term: "ARIA", def: "Accessible Rich Internet Applications: a W3C specification of attributes that enhance accessibility semantics.", lesson: 7, tags: ["aria"] },
      { term: "Keyboard focus", def: "The active state indicating which interactive element currently receives keyboard input events.", lesson: 7, tags: ["a11y"] },
      { term: "DevTools Elements panel", def: "An interactive browser tool for inspecting, modifying, and debugging live DOM nodes and styles.", lesson: 8, tags: ["tools"] }
    ]
  }
];
